### ISSUE TITLE
Cell returned null on integer 0

### ISSUE THREAD

**Issue by samjay** [lappsgrid-incubator/jupyter-groovy-kernel#12]
We've noticed a bug in the kernel where if the script.run() returns a integer with value 0, then it casts as a null object and will return "cell returned null" on the output. 
https://github.com/lappsgrid-incubator/jupyter-groovy-kernel/blob/master/src/main/groovy/org/lappsgrid/jupyter/groovy/handler/ExecuteHandler.groovy#L117

**Comment by ksuderman** [comment]
Thanks for the bug report @samjay.  I've pushed a fixed version (1.2.1) to Maven Central and a new Docker image to hub.docker.com.
